const KEY_LEFT = 37
const KEY_UP = 38
const KEY_RIGHT = 39
const KEY_DOWN = 40
const KEY_SPACE = 32
const KEY_CTRL = 17
const KEY_CMD = 91

const KEY_P = 80

const LEVEL_1_IMG_BG_1 = './img/backgrounds/bg1.png'

const LEVEL_1_IMG_TERRAIN_TOP = [
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  './img/terrain/level-1/mod-low-4.png',
  './img/terrain/level-1/mod-low-3.png',
  './img/terrain/level-1/mod-mid.png',
  './img/terrain/level-1/mod-hig.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-mid.png',
  './img/terrain/level-1/mod-low-0.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-low-4.png',
  './img/terrain/level-1/mod-entrance-bay-1.png',
  './img/terrain/level-1/mod-entrance-bay-2.png',
  './img/terrain/level-1/mod-low-0.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-low-4.png',
]

const LEVEL_1_IMG_TERRAIN_BOTTOM = [
  './img/terrain/level-1/mod-low-4.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-3.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-hig.png',
  './img/terrain/level-1/mod-mid.png',
  './img/terrain/level-1/mod-low-0.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-low-4.png',
  './img/terrain/level-1/mod-low-3.png',
  './img/terrain/level-1/mod-mid.png',
  './img/terrain/level-1/mod-hig.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-mid.png',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  './img/terrain/level-1/mod-low-4.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-mid.png',
  './img/terrain/level-1/mod-low-3.png',
  './img/terrain/level-1/mod-hig.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-mid.png',
  './img/terrain/level-1/mod-low-0.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-low-4.png',
  './img/terrain/level-1/mod-entrance-bay-1.png',
  './img/terrain/level-1/mod-entrance-bay-2.png',
  './img/terrain/level-1/mod-low-0.png',
  './img/terrain/level-1/mod-low-2.png',
  './img/terrain/level-1/mod-low-1.png',
  './img/terrain/level-1/mod-low-4.png',
]

const IMG_PLAYER = './img/sprites/player.png'